"""Application services that compose domain policy with typed ports."""

from .approvals import (
    PendingPlanApproval,
    PlanNotApprovableError,
    ScenarioAApprovalService,
    recompute_plan_hash,
)
from .candidates import (
    SupplierCandidate,
    SupplierCandidateFilter,
    SupplierCandidateResult,
    SupplierExclusion,
    SupplierExclusionReason,
)
from .context import (
    AuthorizedContextBundle,
    MissingScenarioAContextEvidenceError,
    ScenarioAContextAssembler,
    StaleAttentionEvidenceError,
)
from .gate import GateDecision, GateDenialReason, GateStatus, ScenarioAGate
from .planning import (
    EnterWorkflowRecommendation,
    FakeLLMPort,
    InvalidScenarioARecommendationError,
    ManualReviewRecommendation,
    NoActionRecommendation,
    ScenarioARecommendation,
    validate_scenario_a_recommendation,
)
from .stockout import StockoutDetection, StockoutDetector, StockoutRisk
from .tools import (
    TOOL_CATALOG,
    CompensationAction,
    CreateReplacementPOInput,
    FlagShortageToPurchasingInput,
    NotifyProductionInput,
    ReallocateLotInput,
    ReduceOrCancelPOInput,
    ScheduleArrivalCheckInput,
    ToolAuthorizationError,
    ToolDefinition,
    ToolName,
    ToolNotDeclaredError,
    authorize_tool,
    build_tool_idempotency_key,
    tool_definition,
)
from .workflows import (
    DECLARED_WORKFLOWS,
    PO_REROUTE_V1,
    WorkflowDefinition,
    WorkflowNotDeclaredError,
    WorkflowStepDefinition,
    WorkflowStepName,
    declared_workflow,
    workflow_for_recommendation,
)

__all__ = [
    "DECLARED_WORKFLOWS",
    "PO_REROUTE_V1",
    "TOOL_CATALOG",
    "AuthorizedContextBundle",
    "CompensationAction",
    "CreateReplacementPOInput",
    "EnterWorkflowRecommendation",
    "FakeLLMPort",
    "FlagShortageToPurchasingInput",
    "GateDecision",
    "GateDenialReason",
    "GateStatus",
    "InvalidScenarioARecommendationError",
    "ManualReviewRecommendation",
    "MissingScenarioAContextEvidenceError",
    "NoActionRecommendation",
    "NotifyProductionInput",
    "PendingPlanApproval",
    "PlanNotApprovableError",
    "ReallocateLotInput",
    "ReduceOrCancelPOInput",
    "ScenarioAApprovalService",
    "ScenarioAContextAssembler",
    "ScenarioAGate",
    "ScenarioARecommendation",
    "ScheduleArrivalCheckInput",
    "StaleAttentionEvidenceError",
    "StockoutDetection",
    "StockoutDetector",
    "StockoutRisk",
    "SupplierCandidate",
    "SupplierCandidateFilter",
    "SupplierCandidateResult",
    "SupplierExclusion",
    "SupplierExclusionReason",
    "ToolAuthorizationError",
    "ToolDefinition",
    "ToolName",
    "ToolNotDeclaredError",
    "WorkflowDefinition",
    "WorkflowNotDeclaredError",
    "WorkflowStepDefinition",
    "WorkflowStepName",
    "authorize_tool",
    "build_tool_idempotency_key",
    "declared_workflow",
    "recompute_plan_hash",
    "tool_definition",
    "validate_scenario_a_recommendation",
    "workflow_for_recommendation",
]
