"""Application services that compose domain policy with typed ports."""

from .approval_routing import (
    APPROVAL_ESCALATION_TASK_TYPE,
    ApprovalRoutingError,
    ApprovalRoutingOutcome,
    ApprovalRoutingResult,
    ApprovalRoutingService,
)
from .approvals import (
    PendingPlanApproval,
    PlanApprovalService,
    PlanNotApprovableError,
    ScenarioAApprovalService,
    recompute_plan_hash,
)
from .arrival_check import (
    ARRIVAL_CHECK_TASK_TYPE,
    ArrivalCheckError,
    ArrivalCheckOutcome,
    ArrivalCheckResult,
    TuesdayArrivalCheckService,
)
from .audit_explain import AuditExplainer, AuditExplanation, AuditExplanationError
from .candidates import (
    SupplierCandidate,
    SupplierCandidateFilter,
    SupplierCandidateResult,
    SupplierExclusion,
    SupplierExclusionReason,
)
from .context import (
    AuthorizedContextBundle,
    MissingScenarioAContextEvidenceError,
    ScenarioAContextAssembler,
    StaleAttentionEvidenceError,
)
from .gate import GateDecision, GateDenialReason, GateStatus, ScenarioAGate
from .planning import (
    AnyScenarioRecommendation,
    EnterWorkflowRecommendation,
    FakeLLMPort,
    FlagShortageToPurchasingRecommendation,
    InvalidScenarioARecommendationError,
    InvalidScenarioBRecommendationError,
    ManualReviewRecommendation,
    NoActionRecommendation,
    ReallocateAndNotifyRecommendation,
    ScenarioARecommendation,
    ScenarioBRecommendation,
    validate_scenario_a_recommendation,
    validate_scenario_b_recommendation,
)
from .quality_context import (
    MissingScenarioBContextEvidenceError,
    ScenarioBContextAssembler,
    ScenarioBContextBundle,
    StaleScenarioBContextEvidenceError,
)
from .quality_hold import (
    QualityHoldDetection,
    QualityHoldDetector,
    QualityHoldEvidenceError,
    QualityHoldRisk,
)
from .scenario_b_control import (
    ScenarioBControlRejectedError,
    ScenarioBControlResult,
    ScenarioBControlService,
    tool_calls_for_scenario_b_recommendation,
)
from .stockout import StockoutDetection, StockoutDetector, StockoutRisk
from .tools import (
    TOOL_CATALOG,
    CompensationAction,
    CreateReplacementPOInput,
    FlagShortageToPurchasingInput,
    NotifyProductionInput,
    ReallocateLotInput,
    ReduceOrCancelPOInput,
    ScheduleArrivalCheckInput,
    ToolAuthorizationError,
    ToolDefinition,
    ToolName,
    ToolNotDeclaredError,
    authorize_tool,
    build_tool_idempotency_key,
    tool_definition,
)
from .workflow_executor import (
    ScenarioAWorkflowExecutor,
    WorkflowClaimLostError,
    WorkflowExecutionRejectedError,
    WorkflowExternalStepPendingError,
)
from .workflow_state import WorkflowStateInitializationError, WorkflowStateService
from .workflows import (
    DECLARED_WORKFLOWS,
    PO_REROUTE_V1,
    WorkflowDefinition,
    WorkflowNotDeclaredError,
    WorkflowStepDefinition,
    WorkflowStepName,
    declared_workflow,
    workflow_for_recommendation,
)

__all__ = [
    "APPROVAL_ESCALATION_TASK_TYPE",
    "ARRIVAL_CHECK_TASK_TYPE",
    "DECLARED_WORKFLOWS",
    "PO_REROUTE_V1",
    "TOOL_CATALOG",
    "AnyScenarioRecommendation",
    "ApprovalRoutingError",
    "ApprovalRoutingOutcome",
    "ApprovalRoutingResult",
    "ApprovalRoutingService",
    "ArrivalCheckError",
    "ArrivalCheckOutcome",
    "ArrivalCheckResult",
    "AuditExplainer",
    "AuditExplanation",
    "AuditExplanationError",
    "AuthorizedContextBundle",
    "CompensationAction",
    "CreateReplacementPOInput",
    "EnterWorkflowRecommendation",
    "FakeLLMPort",
    "FlagShortageToPurchasingInput",
    "FlagShortageToPurchasingRecommendation",
    "GateDecision",
    "GateDenialReason",
    "GateStatus",
    "InvalidScenarioARecommendationError",
    "InvalidScenarioBRecommendationError",
    "ManualReviewRecommendation",
    "MissingScenarioAContextEvidenceError",
    "MissingScenarioBContextEvidenceError",
    "NoActionRecommendation",
    "NotifyProductionInput",
    "PendingPlanApproval",
    "PlanApprovalService",
    "PlanNotApprovableError",
    "QualityHoldDetection",
    "QualityHoldDetector",
    "QualityHoldEvidenceError",
    "QualityHoldRisk",
    "ReallocateAndNotifyRecommendation",
    "ReallocateLotInput",
    "ReduceOrCancelPOInput",
    "ScenarioAApprovalService",
    "ScenarioAContextAssembler",
    "ScenarioAGate",
    "ScenarioARecommendation",
    "ScenarioAWorkflowExecutor",
    "ScenarioBContextAssembler",
    "ScenarioBContextBundle",
    "ScenarioBControlRejectedError",
    "ScenarioBControlResult",
    "ScenarioBControlService",
    "ScenarioBRecommendation",
    "ScheduleArrivalCheckInput",
    "StaleAttentionEvidenceError",
    "StaleScenarioBContextEvidenceError",
    "StockoutDetection",
    "StockoutDetector",
    "StockoutRisk",
    "SupplierCandidate",
    "SupplierCandidateFilter",
    "SupplierCandidateResult",
    "SupplierExclusion",
    "SupplierExclusionReason",
    "ToolAuthorizationError",
    "ToolDefinition",
    "ToolName",
    "ToolNotDeclaredError",
    "TuesdayArrivalCheckService",
    "WorkflowClaimLostError",
    "WorkflowDefinition",
    "WorkflowExecutionRejectedError",
    "WorkflowExternalStepPendingError",
    "WorkflowNotDeclaredError",
    "WorkflowStateInitializationError",
    "WorkflowStateService",
    "WorkflowStepDefinition",
    "WorkflowStepName",
    "authorize_tool",
    "build_tool_idempotency_key",
    "declared_workflow",
    "recompute_plan_hash",
    "tool_calls_for_scenario_b_recommendation",
    "tool_definition",
    "validate_scenario_a_recommendation",
    "validate_scenario_b_recommendation",
    "workflow_for_recommendation",
]
